# Reading Maccor .txt files

In [1]:
%load_ext autoreload
%autoreload 2

In [16]:
from pathlib import Path

import ipywidgets
from ipywidgets import interact, interactive, fixed, interact_manual
import hvplot.pandas
import holoviews as hv
import pandas as pd

import cellpy

In [3]:
pd.options.display.max_rows = 100
pd.options.display.max_columns = 100

In [4]:
data_dir = Path(r"C:\scripts\cellpy_dev_resources\2021_leafs_data\Charge-Discharge\Maccor series 4000")
print(f"Exists? {data_dir.is_dir()}")

for f in data_dir.glob("*.txt"):
    print(f)

Exists? True
C:\scripts\cellpy_dev_resources\2021_leafs_data\Charge-Discharge\Maccor series 4000\01_UBham_M50_Validation_0deg_01.txt
C:\scripts\cellpy_dev_resources\2021_leafs_data\Charge-Discharge\Maccor series 4000\01_WMG_Example MACCOR_cycling number.TXT
C:\scripts\cellpy_dev_resources\2021_leafs_data\Charge-Discharge\Maccor series 4000\01_WMG_Example MACCOR_voltage profiles.TXT

In [5]:
data_file = data_dir / "01_UBham_M50_Validation_0deg_01.txt"
print(f"Exists? {data_file.is_file()}")

Exists? True

In [6]:
pd.read_csv(data_file)

,Today's Date:\t14 December 2020\tDate of Test:\t11 December 2020,12:22:12 PM
0,Filename:\tM50_Validation_0deg_01\tTester Chan...,NaN
1,Procedure:\tM50_Validation.000\tDescription:\t,NaN
2,Rec#\tCyc#\tStep\tTestTime\tStepTime\tAmp-hr\t...,NaN
3,1\t0\t1\t 0d 00:00:0\t 0d 00:00:0\t0.00000\t...,NaN
4,2\t0\t1\t 0d 00:00:5\t 0d 00:00:5\t0.00000\t...,NaN
...,...,...
6702,6700\t0\t23\t 2d 02:51:21.5799999237061\t 0d...,NaN
6703,6701\t0\t23\t 2d 02:51:51.5800018310547\t 0d...,NaN
6704,6702\t0\t23\t 2d 02:52:21.5799999237061\t 0d...,NaN
6705,6703\t0\t23\t 2d 02:52:51.5699996948242\t 0d...,NaN
6706,6704\t0\t24\t 2d 02:52:51.5699996948242\t 0d...,NaN

In [7]:
df = pd.read_csv(data_file, sep="\t", skiprows=2, header=1)
df.head()

,Rec#,Cyc#,Step,TestTime,StepTime,Amp-hr,Watt-hr,Amps,Volts,State,ES,DPt Time,ACImp/Ohms,DCIR/Ohms,Aux #1,Units,Aux #2,Units.1,Aux #3,Units.2,Aux #4,Units.3,Aux #5,Units.4,Aux #6,Units.5,Aux #7,Units.6,Aux #8,Units.7,Aux #9,Units.8,Aux #10,Units.9,Aux #11,Units.10,Aux #12,Units.11,Aux #13,Units.12,Aux #14,Units.13,Aux #15,Units.14,Aux #16,Units.15,VAR1,VAR2,VAR3,VAR4,VAR5,VAR6,VAR7,VAR8,VAR9,VAR10,VAR11,VAR12,VAR13,VAR14,VAR15,Unnamed: 61
0,1,0,1,0d 00:00:0,0d 00:00:0,0.00000,0.00000,0.00000,3.46250,R,0,12/11/2020 12:22:12,0.0,0.0,-2501.71411,C,-2526.14868,C,-2504.47607,C,-2530.44067,C,-2529.66528,C,-2501.96289,C,-2527.44531,C,-2522.9729,C,-2526.66553,C,-2496.17847,C,-2524.49707,C,-2533.96411,C,-2505.04785,C,-2514.50024,C,-2516.68506,C,-2541.54663,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,2,0,1,0d 00:00:5,0d 00:00:5,0.00000,0.00000,0.00000,3.46197,R,129,12/11/2020 12:22:17,0.0,0.0,-2501.84326,C,-2526.14868,C,-2504.47607,C,-2530.44067,C,-2529.53540,C,-2502.09155,C,-2527.44531,C,-2522.9729,C,-2526.79541,C,-2496.17847,C,-2524.49707,C,-2533.96411,C,-2505.04785,C,-2514.50024,C,-2516.68506,C,-2541.54663,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,3,0,2,0d 00:00:5.05000019073486,0d 00:00:0.0500000007450581,0.00000,0.00002,0.50401,3.41627,D,0,12/11/2020 12:22:17,0.0,0.0,-2501.84326,C,-2526.14868,C,-2504.47607,C,-2530.44067,C,-2529.53540,C,-2502.09155,C,-2527.44531,C,-2522.9729,C,-2526.79541,C,-2496.17847,C,-2524.49707,C,-2533.96411,C,-2505.04785,C,-2514.50024,C,-2516.68506,C,-2541.54663,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,4,0,2,0d 00:00:9.3100004196167,0d 00:00:4.30999994277954,0.00060,0.00203,0.50011,3.41115,D,5,12/11/2020 12:22:21,0.0,0.0,-2501.84326,C,-2526.14868,C,-2504.47607,C,-2530.44067,C,-2529.53540,C,-2502.09155,C,-2527.44531,C,-2522.9729,C,-2526.79541,C,-2496.17847,C,-2524.49707,C,-2533.96411,C,-2505.04785,C,-2514.50024,C,-2516.68506,C,-2541.54663,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,5,0,2,0d 00:00:30.8799991607666,0d 00:00:25.8799991607666,0.00359,0.01225,0.50004,3.40604,D,5,12/11/2020 12:22:43,0.0,0.0,-2501.84326,C,-2526.14868,C,-2504.60522,C,-2530.44067,C,-2529.53540,C,-2501.96289,C,-2527.57520,C,-2522.9729,C,-2526.79541,C,-2496.17847,C,-2524.49707,C,-2533.96411,C,-2505.04785,C,-2514.50024,C,-2516.68506,C,-2541.54663,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [8]:
df.describe()

,Rec#,Cyc#,Step,Amp-hr,Watt-hr,Amps,Volts,ES,ACImp/Ohms,DCIR/Ohms,Aux #1,Aux #2,Aux #3,Aux #4,Aux #5,Aux #6,Aux #7,Aux #8,Aux #9,Aux #10,Aux #11,Aux #12,Aux #13,Aux #14,Aux #15,Aux #16,VAR1,VAR2,VAR3,VAR4,VAR5,VAR6,VAR7,VAR8,VAR9,VAR10,VAR11,VAR12,VAR13,VAR14,VAR15,Unnamed: 61
count,6704.000000,6704.0,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.0,6704.0,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.000000,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,6704.0,0.0
mean,3352.500000,0.0,11.504624,1.092704,4.087220,0.937777,3.720595,2.001342,0.0,0.0,-2501.788047,-2526.146200,-2504.511825,-2530.424067,-2529.556091,-2501.980738,-2527.454978,-2522.979971,-2526.784464,-2496.183517,-2524.478873,-2533.965801,-2505.050619,-2514.503257,-2516.687009,-2541.548338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
std,1935.422435,0.0,6.003627,1.287423,4.673429,1.685949,0.463487,8.043528,0.0,0.0,0.064052,0.029829,0.057834,0.045134,0.047535,0.044476,0.034095,0.029471,0.036911,0.028491,0.045203,0.024292,0.019723,0.019546,0.016385,0.015643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
min,1.000000,0.0,1.000000,0.000000,0.000000,0.000000,2.500040,0.000000,0.0,0.0,-2501.971920,-2526.278560,-2504.605220,-2530.570560,-2529.665280,-2502.091550,-2527.575200,-2523.102780,-2526.925290,-2496.307130,-2524.626950,-2534.094240,-2505.176760,-2514.629880,-2516.814450,-2541.676760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
25%,1676.750000,0.0,7.000000,0.000000,0.000000,0.000000,3.366735,1.000000,0.0,0.0,-2501.843260,-2526.148680,-2504.605220,-2530.440670,-2529.535400,-2501.962890,-2527.445310,-2522.972900,-2526.795410,-2496.178470,-2524.497070,-2533.964110,-2505.047850,-2514.500240,-2516.685060,-2541.546630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
50%,3352.500000,0.0,10.000000,0.663995,2.646865,0.499960,3.795760,1.000000,0.0,0.0,-2501.843260,-2526.148680,-2504.476070,-2530.440670,-2529.535400,-2501.962890,-2527.445310,-2522.972900,-2526.795410,-2496.178470,-2524.497070,-2533.964110,-2505.047850,-2514.500240,-2516.685060,-2541.546630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
75%,5028.250000,0.0,16.250000,1.735742,6.450100,1.499890,4.179370,1.000000,0.0,0.0,-2501.714110,-2526.148680,-2504.476070,-2530.440670,-2529.535400,-2501.962890,-2527.445310,-2522.972900,-2526.795410,-2496.178470,-2524.497070,-2533.964110,-2505.047850,-2514.500240,-2516.685060,-2541.546630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
max,6704.000000,0.0,24.000000,4.544030,16.563700,10.018310,4.200120,193.000000,0.0,0.0,-2501.585450,-2526.018800,-2504.346920,-2530.310790,-2529.535400,-2501.962890,-2527.445310,-2522.972900,-2526.665530,-2496.049800,-2524.367430,-2533.834230,-2504.918950,-2514.500240,-2516.555420,-2541.416260,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [9]:
# df.dtypes

In [10]:
cols = list(df.columns)
cols.remove("TestTime")
cols

['Rec#',
 'Cyc#',
 'Step',
 'StepTime',
 'Amp-hr',
 'Watt-hr',
 'Amps',
 'Volts',
 'State',
 'ES',
 'DPt Time',
 'ACImp/Ohms',
 'DCIR/Ohms',
 'Aux #1',
 ' Units',
 'Aux #2',
 ' Units.1',
 'Aux #3',
 ' Units.2',
 'Aux #4',
 ' Units.3',
 'Aux #5',
 ' Units.4',
 'Aux #6',
 ' Units.5',
 'Aux #7',
 ' Units.6',
 'Aux #8',
 ' Units.7',
 'Aux #9',
 ' Units.8',
 'Aux #10',
 ' Units.9',
 'Aux #11',
 ' Units.10',
 'Aux #12',
 ' Units.11',
 'Aux #13',
 ' Units.12',
 'Aux #14',
 ' Units.13',
 'Aux #15',
 ' Units.14',
 'Aux #16',
 ' Units.15',
 'VAR1',
 'VAR2',
 'VAR3',
 'VAR4',
 'VAR5',
 'VAR6',
 'VAR7',
 'VAR8',
 'VAR9',
 'VAR10',
 'VAR11',
 'VAR12',
 'VAR13',
 'VAR14',
 'VAR15',
 'Unnamed: 61']

In [11]:
@interact(y=cols)
def g(y):
    try:
        p = df.plot(x="TestTime", y=y)
        return p
    except:
        return df[y].head()

interactive(children=(Dropdown(description='y', options=('Rec#', 'Cyc#', 'Step', 'StepTime', 'Amp-hr', 'Watt-hâ€¦

## Pre-processing

In [12]:
keep = [
    'Rec#',
    'Cyc#',
    'Step',
    'StepTime',
    'Amp-hr',
    'Watt-hr',
    'Amps',
    'Volts',
    'State',
    'ES',
    'DPt Time',
    'ACImp/Ohms',
    'DCIR/Ohms',
]

In [13]:
@interact(y=keep)
def g(y):
    try:
        p = df.plot(x="TestTime", y=y)
        return p
    except:
        return df[y].head()

interactive(children=(Dropdown(description='y', options=('Rec#', 'Cyc#', 'Step', 'StepTime', 'Amp-hr', 'Watt-hâ€¦

In [24]:
df2 = df[keep]

In [ ]:
unit_labels = {
    "time": "s",
    "current": "A",
    "voltage": "V",
    "power": "W",
    "capacity": "Ah",
    "energy": "Wh",
    "resistance": "Ohms",
    "temperature": "C",
}


normal_headers_renaming_dict = {
    "data_point_txt": f"Rec#",
    "datetime_txt": f"DPt Time",
   # "test_time_txt": f"Test_Time({unit_labels['time']})",
    "step_time_txt": f"StepTime",
    "cycle_index_txt": f"Cyc#",
    "step_index_txt": f"Step",
    #"sub_step_index_txt": f"Sub_Step_Index",  # new
    #"sub_step_time_txt": f"Sub_Step_Time",  # new
    "current_txt": f"Amps",
    "voltage_txt": f"Volts",
    "power_txt": f"Watt-hr",  # TODO: include the new cols into internal settings
    
    
    "charge_capacity_txt": f"Amp-hr",
    "charge_energy_txt": f"Watt-hr",
    #"discharge_capacity_txt": f"Discharge_Capacity({unit_labels['capacity']})",
    
    #"discharge_energy_txt": f"Discharge_Energy({unit_labels['energy']})",
    #"acr_txt": f"Internal_Resistance({unit_labels['resistance']})",  # TODO: include the new cols into internal settings
    "internal_resistance_txt": f"DCIR{unit_labels['resistance']}",
    #"dv_dt_txt": f"dV/dt({incremental_unit_labels['dv_dt']})",  # TODO: include the new cols into internal settings
    #"dq_dv_txt": f"dV/dt({incremental_unit_labels['dq_dv']})",  # TODO: include the new cols into internal settings
    #"dv_dq_txt": f"dV/dt({incremental_unit_labels['dv_dq']})",  # TODO: include the new cols into internal settings
    #"aci_phase_angle_txt": f"ACI_Phase_Angle",  # not observed yet
    #"ref_aci_phase_angle_txt": f"Reference_ACI_Phase_Angle",
    "ac_impedance_txt": f"ACImp/{unit_labels['resistance']}",
    #"ref_ac_impedance_txt": f"Reference_AC_Impedance",
    #"is_fc_data_txt": f"Is_FC_Data",
    #"test_id_txt": f"Test_ID",
    #"ref_voltage_txt": f"Reference_Voltage({unit_labels['resistance']})",  # new
    #"frequency_txt": f"Frequency",  # new
    #"amplitude_txt": f"Amplitude",  # new
    #"channel_id_txt": f"Channel_ID",  # new Arbin SQL Server
    #"data_flag_txt": f"Data_Flags",  # new Arbin SQL Server
    #"test_name_txt": f"Test_Name",  # new Arbin SQL Server

In [26]:
rename = {
    'Rec#': ,
     'Cyc#',
     'Step',
     'StepTime',
     'Amp-hr',
     'Watt-hr',
     'Amps',
     'Volts',
     'State',
     'ES',
     'DPt Time',
     'ACImp/Ohms',
     'DCIR/Ohms'
}

['Rec#',
 'Cyc#',
 'Step',
 'StepTime',
 'Amp-hr',
 'Watt-hr',
 'Amps',
 'Volts',
 'State',
 'ES',
 'DPt Time',
 'ACImp/Ohms',
 'DCIR/Ohms']

In [25]:
df2

,Rec#,Cyc#,Step,StepTime,Amp-hr,Watt-hr,Amps,Volts,State,ES,DPt Time,ACImp/Ohms,DCIR/Ohms
0,1,0,1,0d 00:00:0,0.00000,0.00000,0.00000,3.46250,R,0,12/11/2020 12:22:12,0.0,0.0
1,2,0,1,0d 00:00:5,0.00000,0.00000,0.00000,3.46197,R,129,12/11/2020 12:22:17,0.0,0.0
2,3,0,2,0d 00:00:0.0500000007450581,0.00000,0.00002,0.50401,3.41627,D,0,12/11/2020 12:22:17,0.0,0.0
3,4,0,2,0d 00:00:4.30999994277954,0.00060,0.00203,0.50011,3.41115,D,5,12/11/2020 12:22:21,0.0,0.0
4,5,0,2,0d 00:00:25.8799991607666,0.00359,0.01225,0.50004,3.40604,D,5,12/11/2020 12:22:43,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6699,6700,0,23,0d 01:58:30.0100002288818,0.00000,0.00000,0.00000,3.55116,R,1,12/13/2020 15:13:43,0.0,0.0
6700,6701,0,23,0d 01:59:0.00999999977648258,0.00000,0.00000,0.00000,3.55123,R,1,12/13/2020 15:14:13,0.0,0.0
6701,6702,0,23,0d 01:59:30.0100002288818,0.00000,0.00000,0.00000,3.55123,R,1,12/13/2020 15:14:43,0.0,0.0
6702,6703,0,23,0d 02:00:0,0.00000,0.00000,0.00000,3.55123,R,129,12/13/2020 15:15:13,0.0,0.0
6703,6704,0,24,0d 02:00:0,0.00000,0.00000,0.00000,3.55131,O,193,12/13/2020 15:15:13,0.0,0.0

In [19]:
@interact(y=keep)
def g(y):
    try:
        p = df.hvplot(x="TestTime", y=y)
        return p
    except:
        return df[y].head()

interactive(children=(Dropdown(description='y', options=('Rec#', 'Cyc#', 'Step', 'StepTime', 'Amp-hr', 'Watt-hâ€¦

In [22]:
df.TestTime.astype()

AttributeError: 'Series' object has no attribute 'to_datetime'